sudo: required
services:
  - docker

before_install:
  - docker build -t sstone19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sstone19/react-test npm run test

after_success:
  - docker build -t sstone19/multi-client ./client
  - docker build -t sstone19/multi-nginx ./nginx
  - docker build -t sstone19/multi-server ./server
  - docker build -t sstone19/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sstone19/multi-client
  - docker push sstone19/multi-nginx
  - docker push sstone19/multi-server
  - docker push sstone19/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-244502094993"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
